Vagrant.configure("2") do |config|
  config.vm.box = "dvsm48qnzqag/centos7-kernel6"
  config.vm.define "otus-task1"
  config.vm.synced_folder "./", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
end
